#!/bin/bash
##
# CU - C unit testing framework
# ---------------------------------
# Copyright (c)2007 Daniel Fiser <danfis@danfis.cz>
#
#
#  This file is part of CU.
#
#  CU is free software; you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as
#  published by the Free Software Foundation; either version 3 of
#  the License, or (at your option) any later version.
#
#  CU is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

DIR="$1"
TMP="/tmp/$$.regression.test"
RET=0

for file in $(ls tmp.*); do
    file_orig=${file#tmp.}

    if [ -f "$file_orig" ]; then
        echo -ne "Comparing $file and $file_orig:"
        diff $file_orig $file >$TMP 2>&1;
        if [ $? -eq 0 ]; then
            echo -ne " \033[0;32mOK\033[0;0m\n";
        else
            echo -ne " \033[0;31mFAILED\033[0;0m\n";
            echo "diff $file_orig $file:"
            cat $TMP;
            RET=1
        fi
    else
        echo "Can't compare $file $file_orig, bacause $file_orig does not exist!"
        RET=1
    fi
done;

rm -f $TMP
exit $RET
